name: 农场管理系统库存
description: 为数量添加库存功能。
type: module
package: 农场管理系统
core_version_requirement: ^11
dependencies:
  - drupal:options
  - farm:asset
  - farm:farm_field
  - farm:farm_log_quantity
  - farm:quantity
  - fraction:fraction
